name: Manual Trigger Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get sources
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: pip install --upgrade -r requirements.txt --quiet

      - name: Make the script
        run: |
          cat << EOF > run.py
          from todoist_api_python.api import TodoistAPI
          from tools.random_task import run

          api = TodoistAPI('${{ secrets.TODOIST_TOKEN }}')
          run(api, "Może kiedyś")
          EOF

      - name: Run the script
        run: python run.py
