name: Reproduce by forgetting curve

on:  
  push:
  pull_request:
  schedule:
    - cron: '36 18 * * *'

jobs:
  make_schedule_on_week:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get sources
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: pip install --upgrade -r requirements.txt --quiet

      - name: Make the script
        run: |
          cat << EOF > run.py
          from todoist_api_python.api import TodoistAPI
          from tools.reproduce_by_forgetting_curve import run

          api = TodoistAPI('${{ secrets.TODOIST_TOKEN }}')
          run(api, "wishtoremember", 5)
          EOF

      - name: Run the script
        run: python run.py
